return {
	"nvim-treesitter/nvim-treesitter",
	enabled = true,
	build = ":TSUpdate",
	config = function()
		local config = require("nvim-treesitter.configs")
		config.setup({
			ensure_installed = {
				"bash",
				"c",
				"css",
				"dockerfile",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"gotmpl",
				"gowork",
				"graphql",
				"html",
				"javascript",
				"jsdoc",
				"json",
				"json5",
				"lua",
				"markdown",
				"php",
				"phpdoc",
				"proto",
				"python",
				"robots",
				"scss",
				"sql",
				"tsx",
				"toml",
				"tmux",
				"typescript",
				"vimdoc",
				"vue",
				"xml",
				"yaml",
				"java",
				"c_sharp",
			},
			auto_install = true,
			sync_install = false,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = false,
			},
			indent = { enable = true },
		})
	end,
}
